adminbi/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        re_path("", include("apps.home.urls")),
        re_path("", include("apps.users.urls")),
        re_path("", include("apps.bi.urls")),
        re_path("", include("apps.cargues.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

apps/bi/urls.py
#
from django.urls import path

from . import views

app_name = "bi_app"

urlpatterns = [
    path(
        'actualizacion-bi/', 
        views.ActualizacionBiPage.as_view(),
        name='actualizacion_bi',
    ),
    # path(
    #     'reporte-bi/', 
    #     views.EmbedReportPage.as_view(),
    #     name='reporte_bi',
    # ),
    path(
        'reporte_embed/', 
        views.IncrustarBiPage.as_view(),
        name='reporte_embed',
    ),
    # path('embed_info/', views.EmbedInfoView.as_view(), name='embed_info'),
    path('reporte_embed2/', views.reporte_embed, name='reporte_embed2'),
    path('eliminar_reporte_fetched/', views.EliminarReporteFetched.as_view(), name='eliminar_reporte_fetched'),
    
]

apps/home/urls.py
#
from django.urls import path

from . import views

app_name = "home_app"

urlpatterns = [
    path(
        'panel/', 
        views.HomePage.as_view(),
        name='panel',
    ),
    path(
        'panel_left_planos/', 
        views.HomePage.as_view(),
        name='panel_left_planos',
    ),
    path(
        'cubo/', 
        views.CuboPage.as_view(), 
        name='cubo',
    ),
    path(
        'interface/', 
        views.InterfacePage.as_view(), 
        name='interface',
    ),
    path(
        'actualizacion/', 
        views.ActualizacionPage.as_view(), 
        name='actualizacion',
    ),
    path(
        'plano/', 
        views.PlanoPage.as_view(), 
        name='plano',
    ),
    path(
        'prueba/', 
        views.PruebaPage.as_view(), 
        name='prueba',
    ),
   path('download_file/', views.DownloadFileView.as_view(), name='download_file'),
   path('delete_file/', views.DeleteFileView.as_view(), name='delete_file'),
   path('check-task-status/', views.CheckTaskStatusView.as_view(), name='check_task_status'),
]

apps/home/models.py
from django.db import models

# Create your models here.

apps/home/views.py
from django.contrib import messages
import subprocess
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
import os
from django.http import HttpResponse, FileResponse, JsonResponse
import io
from django.views.generic import View
from django.utils.decorators import method_decorator
from apps.users.decorators import registrar_auditoria
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect
from scripts.conexion import Conexion
from scripts.config import ConfigBasic
from scripts.StaticPage import StaticPage, DinamicPage
from scripts.extrae_bi.extrae_bi_call import Extrae_Bi
from scripts.extrae_bi.interface import InterfaceContable
from django.contrib.auth.mixins import UserPassesTestMixin
from .tasks import cubo_ventas_task, interface_task, plano_task, extrae_bi_task
from django.http import JsonResponse
from django.views import View

# importaciones para celery
# from celery.result import AsyncResult

# importaciones para rq
from django_rq import get_queue
from rq.job import Job
from rq.job import NoSuchJobError
from django_rq import get_connection

from django.views.generic import TemplateView
from apps.users.views import BaseView


class HomePage(LoginRequiredMixin, BaseView):
    template_name = "home/panel.html"

    login_url = reverse_lazy("users_app:user-login")

    def post(self, request, *args, **kwargs):
        request.session["template_name"] = self.template_name
        database_name = request.POST.get("database_select")
        if not database_name:
            return redirect("home_app:panel")

        request.session["database_name"] = database_name
        StaticPage.name = database_name

        return redirect("home_app:panel")

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form_url"] = "home_app:panel"
        return context


class DownloadFileView(BaseView):
    login_url = reverse_lazy("users_app:user-login")

    def get(self, request):
        template_name = request.session.get("template_name", "home/panel.html")
        file_path = request.session.get("file_path")
        file_name = request.session.get("file_name")

        f = None  # Define f fuera del bloque try para que esté disponible en el bloque except

        if file_path and file_name:
            try:
                f = open(file_path, "rb")
                response = FileResponse(f)
                response["Content-Disposition"] = f'attachment; filename="{file_name}"'
                return response
            except IOError:
                # Si f ha sido asignado y está abierto, ciérralo.
                if f:
                    f.close()
                messages.error(request, "Error al abrir el archivo")
        else:
            messages.error(request, "Archivo no encontrado")
        return render(request, "home/panel.html", {"template_name": template_name})


class DeleteFileView(BaseView):
    login_url = reverse_lazy("users_app:user-login")

    def post(self, request):
        template_name = request.session.get("template_name")
        file_path = request.session.get("file_path")

        if file_path is None:
            return JsonResponse(
                {"success": False, "error_message": "No hay archivo para eliminar."}
            )

        try:
            os.remove(file_path)
            # Borra la ruta del archivo y el nombre del archivo de la sesión.
            del request.session["file_path"]
            del request.session["file_name"]
            return HttpResponseRedirect(reverse(self.template_name))
        except FileNotFoundError:
            return JsonResponse(
                {"success": False, "error_message": "El archivo no existe."}
            )
        except Exception as e:
            return JsonResponse(
                {
                    "success": False,
                    "error_message": f"Error: no se pudo ejecutar el script. Razón: {str(e)}",
                }
            )


class CheckTaskStatusView(BaseView):
    """
    Vista para comprobar el estado de una tarea asincrónica y recuperar su resultado.

    Esta vista espera recibir un ID de tarea y devuelve el estado de la tarea,
    así como su resultado si la tarea ha finalizado correctamente.
    """

    def post(self, request, *args, **kwargs):
        """
        Maneja la solicitud POST para comprobar el estado de una tarea asincrónica.

        :param request: Objeto HttpRequest.
        :return: JsonResponse con el estado de la tarea o un mensaje de error.
        """
        task_id = request.POST.get("task_id")
        if not task_id:
            return JsonResponse({"error": "No task ID provided"}, status=400)

        connection = get_connection()
        try:
            job = Job.fetch(task_id, connection=connection)
            if job.is_finished:
                return self.handle_finished_job(request, job)
            elif job.is_failed:
                return JsonResponse({"error": "Task execution failed"}, status=500)
            else:
                return JsonResponse({"status": job.get_status()})

        except NoSuchJobError:
            return JsonResponse({"status": "notfound", "error": "Task not found"})
        


    def handle_finished_job(self, request, job):
        """
        Maneja el caso cuando una tarea ha finalizado.

        :param request: Objeto HttpRequest.
        :param job: Objeto Job que representa la tarea finalizada.
        :return: JsonResponse con el resultado de la tarea o un mensaje de error.
        """
        resultado = job.result
        if resultado is None:
            return JsonResponse({"error": "Task finished with no result"}, status=500)

        # Si el resultado fue exitoso pero no incluye los detalles del archivo, continúa de todas formas
        if resultado.get("success"):
            response_data = {"status": "finished", "result": resultado}

            # Solo agrega file_path y file_name a la sesión si están presentes
            if "file_path" in resultado and "file_name" in resultado:
                request.session["file_path"] = resultado["file_path"]
                request.session["file_name"] = resultado["file_name"]
                # Podrías querer incluir también esta información en la respuesta
                response_data.update({"file_path": resultado["file_path"], "file_name": resultado["file_name"]})

            return JsonResponse(response_data)

        # Si el resultado no fue exitoso o no cumple con las expectativas
        return JsonResponse(
            {"error": "Task completed but result is not as expected"}, status=500
        )



class CuboPage(LoginRequiredMixin, BaseView):
    """
    Vista para la página de generación del Cubo de Ventas.

    Esta vista maneja la solicitud del usuario para generar un cubo de ventas,
    iniciando una tarea en segundo plano y devolviendo el ID de dicha tarea.
    """

    # Nombre de la plantilla a utilizar para renderizar la vista
    template_name = "home/cubo.html"

    # URL para redirigir en caso de que el usuario no esté autenticado
    login_url = reverse_lazy("users_app:user-login")

    @method_decorator(registrar_auditoria)
    @method_decorator(permission_required("permisos.cubo", raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        """
        Método para despachar la solicitud, aplicando decoradores de auditoría y
        permisos requeridos.
        """
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """
        Maneja la solicitud POST para iniciar el proceso de generación del cubo de ventas.

        Recoge los datos del formulario, valida la entrada y, si es válida,
        inicia una tarea asincrónica para generar el cubo de ventas.
        """
        database_name = request.POST.get("database_select")
        IdtReporteIni = request.POST.get("IdtReporteIni")
        IdtReporteFin = request.POST.get("IdtReporteFin")
        request.session["template_name"] = self.template_name

        if not all([database_name, IdtReporteIni, IdtReporteFin]):
            return JsonResponse(
                {
                    "success": False,
                    "error_message": "Se debe seleccionar la base de datos y las fechas.",
                },
                status=400,
            )

        try:
            task = cubo_ventas_task.delay(database_name, IdtReporteIni, IdtReporteFin)
            request.session["task_id"] = task.id
            return JsonResponse({"success": True, "task_id": task.id})
        except Exception as e:
            return JsonResponse(
                {"success": False, "error_message": f"Error: {str(e)}"}, status=500
            )

    def get(self, request, *args, **kwargs):
        """
        Maneja la solicitud GET, devolviendo la plantilla de la página del cubo de ventas.
        """
        database_name = request.session.get("database_name")
        if not database_name:
            messages.warning(request, "Debe seleccionar una empresa antes de continuar.")
            return redirect("home_app:panel")

        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        """
        Obtiene el contexto necesario para la plantilla.

        :return: Contexto que incluye la URL del formulario.
        """
        context = super().get_context_data(**kwargs)
        context["form_url"] = "home_app:cubo"
        return context


class InterfacePage(LoginRequiredMixin, BaseView):
    """

templates/home/actualizacion.html
{% extends 'black.html' %}
{% load static %}

{% block title %}
Actualización
{% endblock title %}

{% block window %}
{% include 'includes/datepicker_range.html' %}
<!-- contenido de la pagina -->
<br>
<br>
<div class="card" style="width: 25rem;">
  <div class="card-header text-center">
    <h2>Actualizar Base de Datos</h2>
  </div>
  <div class="card-body">
    <label for="date_input">Fecha:</label>
    <div id="reportrange"
      style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%">
      <i class="fa fa-calendar"></i>&nbsp;
      <span></span> <i class="fa fa-caret-down"></i>
    </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th><label class="lh-1" for="IdtReporteIni">Fecha Inicial:</label></th>
          <th><label class="lh-1" for="IdtReporteFin">Fecha Final:</label></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th><input type="date" name="IdtReporteIni" id="IdtReporteIni" readonly></th>
          <th><input type="date" name="IdtReporteFin" id="IdtReporteFin" readonly></th>
        </tr>
      </tbody>
    </table>
    <br>
    <!-- Pestañas -->
    <ul class="nav nav-tabs" id="actualizacionTabs" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="base-datos-tab" data-bs-toggle="tab" data-bs-target="#base-datos"
          type="button" role="tab" aria-controls="base-datos" aria-selected="true">Base de Datos</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="powerbi-tab" data-bs-toggle="tab" data-bs-target="#powerbi" type="button"
          role="tab" aria-controls="powerbi" aria-selected="false">PowerBi</button>
      </li>
    </ul>
    <div class="tab-content" id="actualizacionTabsContent">
      <div class="tab-pane fade show active" id="base-datos" role="tabpanel" aria-labelledby="base-datos-tab">
        <!-- Formulario de actualización de Base de Datos -->
        <p>
        <form action="{% url 'home_app:actualizacion' %}" method="post" id="FormActualizacion">
          {% csrf_token %}
          <span class="card text-center"><button id="submitBtn" type="submit"
              class="btn btn-primary">Actualizar</button></span>
        </form>
        </p>
      </div>
      <div class="tab-pane fade" id="powerbi" role="tabpanel" aria-labelledby="powerbi-tab">
        <!-- Formulario de actualización de PowerBi -->
        <p>
        <form action="{% url 'bi_app:actualizacion_bi' %}" method="post" id="myFormPowerBi">
          {% csrf_token %}
          <span class="card text-center"><button id="submitBtnPowerBi" type="submit"
              class="btn btn-primary">Actualizar</button></span>
        </form>
        </p>
        <h6>Recuerda!!! máximo 3 actualizaciones en un día</h6>
      </div>
    </div>
  </div>
</div>

<!-- Este es el Modal -->
<div class="modal" id="processingModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Actualizando...</h5>
      </div>
      <div class="modal-body">
        Por favor, espere mientras se procesa su actualización...
        <br>
        <hr>
        <div id="powerBiMessage" style="display: none;">
          La actualización del Bi tarda debes de tener paciencia...
          <br>
          <hr>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- final del modal -->
{% endblock window %}

{% block script %}
<script>
  document.getElementById("processingModal").style.display = "none";
  var csrf_token = document.getElementsByName("csrfmiddlewaretoken")[0].value;

  // Evento click para Base de Datos
  document.getElementById("submitBtn").addEventListener("click", function (event) {
    event.preventDefault();
    // Check if a task is already in progress
    if (this.getAttribute("data-submitted") === "true") {
      alert("Ya hay una tarea en curso.");
      return;
    }

    this.setAttribute("data-submitted", "true");
    document.getElementById("processingModal").style.display = "flex";
    showMessage("database");
    submitForm("{% url 'home_app:actualizacion' %}", "FormActualizacion");
  });

  // Evento click para PowerBi
  document.getElementById("submitBtnPowerBi").addEventListener("click", function (event) {
    event.preventDefault();
    // Check if a task is already in progress
    if (this.getAttribute("data-submitted") === "true") {
      alert("Ya hay una tarea en curso.");
      return;
    }

    this.setAttribute("data-submitted", "true");
    document.getElementById("processingModal").style.display = "flex";
    showMessage("powerbi");
    submitForm("{% url 'bi_app:actualizacion_bi' %}", "myFormPowerBi");
  });

  function showMessage(type) {
    var powerBiMessage = document.getElementById("powerBiMessage");
    if (type === "powerbi") {
      powerBiMessage.style.display = "block";
    } else {
      powerBiMessage.style.display = "none";
    }
  }


  function submitForm(url, formId) {
    // Mostrar modal de procesamiento
    document.getElementById("processingModal").style.display = "flex";
    // Preparar datos del formulario
    var formData = new FormData();
    var database = window.sessionStorage.getItem("database_name");
    var IdtReporteIni = document.getElementById("IdtReporteIni").value;
    var IdtReporteFin = document.getElementById("IdtReporteFin").value;
    formData.append("database_select", database);
    formData.append("IdtReporteIni", IdtReporteIni);
    formData.append("IdtReporteFin", IdtReporteFin);

    // Realizar solicitud AJAX
    var xhr = new XMLHttpRequest();
    xhr.open("POST", url, true);
    xhr.setRequestHeader("X-CSRFToken", csrf_token);

    xhr.onload = function () {
      if (xhr.status === 200) {
        try {
          var response = JSON.parse(xhr.responseText);
          handleServerResponse(xhr.status, response);
        } catch (e) {
          alert("Error al procesar la respuesta del servidor.");
          console.error("Error parsing JSON:", e);
        }
      } else {
        alert("Hubo un error al enviar la solicitud, código de estado: " + xhr.status);
      }
    };

    xhr.onerror = function () {
      alert("Error en la solicitud al servidor.");
    };

    xhr.send(formData);
  }

  function checkTaskStatus() {
    var task_id = window.sessionStorage.getItem("task_id");

    var xhr = new XMLHttpRequest();
    xhr.open("POST", "{% url 'home_app:check_task_status' %}", true);
    xhr.setRequestHeader("X-CSRFToken", csrf_token);
    xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");

    xhr.onload = function () {
      if (xhr.status === 200) {
        try {
          var response = JSON.parse(xhr.responseText);
          handleTaskStatus(xhr.status, response);
        } catch (e) {
          alert("Error al procesar la respuesta del servidor.");
          console.error("Error parsing JSON:", e);
        }
      } else {
        alert("Hubo un error al comprobar el estado de la tarea, código de estado: " + xhr.status);
      }
    };

    xhr.onerror = function () {
      alert("Error en la solicitud al servidor.");
    };

    xhr.send("task_id=" + encodeURIComponent(task_id));
  }


  // Manejar la respuesta del servidor
  function handleServerResponse(status, response) {
    if (status === 200) {
      if (typeof response === "object" && "success" in response) {
        if (response.success) {
          // Almacena actualiza_task_id en sessionStorage
          window.sessionStorage.setItem("task_id", response.task_id);
          // Comprueba el estado de la tarea
          checkTaskStatus();
        } else {
          alert("Hubo un error en el proceso: " + response.error_message);
        }
      } else {
        alert("La respuesta del servidor no es un objeto JSON válido");
      }
    } else {
      alert("Hubo un error al enviar la solicitud, código de estado: " + status);
    }
  }

  // función para revisar estatus de la tarea
  function checkTaskStatus() {
    var task_id = window.sessionStorage.getItem("task_id");

    var xhr = new XMLHttpRequest();
    xhr.responseType = "text";
    xhr.open("POST", "{% url 'home_app:check_task_status' %}", true);
    xhr.setRequestHeader("X-CSRFToken", csrf_token);
    xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
    xhr.onreadystatechange = function () {
      if (this.readyState === XMLHttpRequest.DONE) {
        var response = JSON.parse(this.responseText);
        handleTaskStatus(this.status, response);
      }
    };
    xhr.send("task_id=" + encodeURIComponent(task_id));
  }

  // Revisar el estado de la tarea
  function handleTaskStatus(status, response) {
    if (status === 200) {
      if (typeof response === "object" && "status" in response) {
        if (response.status === "finished") {
          // La tarea se ha completado, podemos mostrar el resultado al usuario
          document.getElementById("processingModal").style.display = "none";
          alert("Proceso terminado");
          reloadForm();
        } else if (response.status === "failed") {
          // La tarea falló
          document.getElementById("processingModal").style.display = "none";
          alert("Hubo un error en el proceso: " + response.result);
          reloadForm();
        } else if (response.status === "queued" || response.status === "deferred" || response.status === "started") {
          // La tarea aún se está ejecutando, verifica el estado de nuevo después de un tiempo
          setTimeout(checkTaskStatus, 20000);
        } else {
          alert("Estado desconocido de la tarea: " + response.status);
        }
      } else {
        alert("La respuesta del servidor no es un objeto JSON válido");
      }
    } else {
      alert("Hubo un error al comprobar el estado de la tarea, código de estado: " + status);
    }
  }
  // Función para recargar el formulario después de borrar el archivo
  function reloadForm() {
    location.reload();
  }
</script>
{% endblock script %}

templates/home/actualizacion_cards.html
{% extends 'black.html' %}
{% load static %}

{% block title %}
Actualización
{% endblock title %}

{% block window %}
{% include 'includes/datepicker_range.html' %}
<!-- contenido de la pagina -->
<br>
<br>
<div class="card" style="width: 25rem;">
  <div class="card-header text-center">
    <h2>Actualizar Base de Datos</h2>
  </div>
  <div class="card-body">
    <!-- Pestañas -->
    <ul class="nav nav-tabs" id="actualizacionTabs" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="base-datos-tab" data-bs-toggle="tab" data-bs-target="#base-datos"
          type="button" role="tab" aria-controls="base-datos" aria-selected="true">Base de Datos</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="powerbi-tab" data-bs-toggle="tab" data-bs-target="#powerbi" type="button"
          role="tab" aria-controls="powerbi" aria-selected="false">PowerBi</button>
      </li>
    </ul>
    <div class="tab-content" id="actualizacionTabsContent">
      <div class="tab-pane fade show active" id="base-datos" role="tabpanel" aria-labelledby="base-datos-tab">
        <!-- Formulario de actualización de Base de Datos -->
        <p>
        <form action="{% url 'home_app:actualizacion' %}" method="post" id="FormActualizacion">
          {% csrf_token %}
          <span class="card text-center"><button id="submitBtn" type="submit"
              class="btn btn-primary">Actualizar</button></span>
        </form>
        </p>
      </div>
      <div class="tab-pane fade" id="powerbi" role="tabpanel" aria-labelledby="powerbi-tab">
        <!-- Formulario de actualización de PowerBi -->
        <p>
        <form action="{% url 'bi_app:actualizacion_bi' %}" method="post" id="myFormPowerBi">
          {% csrf_token %}
          <span class="card text-center"><button id="submitBtnPowerBi" type="submit"
              class="btn btn-primary">Actualizar</button></span>
        </form>
        </p>
        <h6>Recuerda!!! máximo 3 actualizaciones en un día</h6>
      </div>
    </div>
  </div>
</div>

<!-- Este es el Modal -->
<div class="modal" id="processingModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Actualizando...</h5>
      </div>
      <div class="modal-body">
        Por favor, espere mientras se procesa su actualización...
        <br>
        <hr>
        <div id="powerBiMessage" style="display: none;">
          Ten en cuenta que una vez termine la actualización debes esperar 5 min. para que se refresquen los datos.
          <br>
          <hr>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- final del modal -->
{% endblock window %}

{% block script %}
<script>
  document.getElementById("processingModal").style.display = "none";
  var csrf_token = document.getElementsByName("csrfmiddlewaretoken")[0].value;

  // Evento click para Base de Datos
  document.getElementById("submitBtn").addEventListener("click", function (event) {
    event.preventDefault();
    // Check if a task is already in progress
    if (this.getAttribute("data-submitted") === "true") {
      alert("Ya hay una tarea en curso.");
      return;
    }

    this.setAttribute("data-submitted", "true");
    document.getElementById("processingModal").style.display = "flex";
    showMessage("database");
    submitForm("{% url 'home_app:actualizacion' %}", "FormActualizacion");
  });

  // Evento click para PowerBi
  document.getElementById("submitBtnPowerBi").addEventListener("click", function (event) {
    event.preventDefault();
    // Check if a task is already in progress
    if (this.getAttribute("data-submitted") === "true") {
      alert("Ya hay una tarea en curso.");
      return;
    }

    this.setAttribute("data-submitted", "true");
    document.getElementById("processingModal").style.display = "flex";
    showMessage("powerbi");
    submitForm("{% url 'bi_app:actualizacion_bi' %}", "myFormPowerBi");
  });

  function showMessage(type) {
    var powerBiMessage = document.getElementById("powerBiMessage");
    if (type === "powerbi") {
      powerBiMessage.style.display = "block";
    } else {
      powerBiMessage.style.display = "none";
    }
  }

  function submitForm(url, formId) {
    document.getElementById("processingModal").style.display = "flex";

    // Realiza la solicitud AJAX al servidor
    var xhr = new XMLHttpRequest();
    xhr.responseType = "text";
    xhr.open("POST", url, true);
    xhr.setRequestHeader("X-CSRFToken", csrf_token);
    xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
    xhr.onreadystatechange = function () {
      if (this.readyState === XMLHttpRequest.DONE) {
        // document.getElementById("processingModal").style.display = "none";
        console.log(this.status, this.responseText);
        var response = JSON.parse(this.responseText);
        handleServerResponse(this.status, response);
      }
    };
    var database = window.sessionStorage.getItem("database_name");
    var formData = new FormData(document.getElementById(formId));
    formData.append("database_select", encodeURIComponent(database));
    xhr.send(new URLSearchParams(formData).toString());
  }

  // Manejar la respuesta del servidor
  function handleServerResponse(status, response) {
    if (status === 200) {
      if (typeof response === "object" && "success" in response) {
        if (response.success) {
          // Almacena interface_task_id en sessionStorage
          window.sessionStorage.setItem("task_id", response.task_id);
          // Comprueba el estado de la tarea
          checkTaskStatus();
        } else {
          alert("Hubo un error en el proceso: " + response.error_message);
        }
      } else {
        alert("La respuesta del servidor no es un objeto JSON válido");
      }
    } else {
      alert("Hubo un error al enviar la solicitud, código de estado: " + status);
    }
  }

  // función para revisar estatus de la tarea
  function checkTaskStatus() {
    var task_id = window.sessionStorage.getItem("task_id");

    var xhr = new XMLHttpRequest();
    xhr.responseType = "text";
    xhr.open("POST", "{% url 'home_app:check_task_status' %}", true);
    xhr.setRequestHeader("X-CSRFToken", csrf_token);
    xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
    xhr.onreadystatechange = function () {
      if (this.readyState === XMLHttpRequest.DONE) {
        var response = JSON.parse(this.responseText);
        handleTaskStatus(this.status, response);
      }
    };
    xhr.send("task_id=" + encodeURIComponent(task_id));
  }

  // Revisar el estado de la tarea
  function handleTaskStatus(status, response) {
    if (status === 200) {
      if (typeof response === "object" && "status" in response) {
        if (response.status === "finished") {
          // La tarea se ha completado, podemos mostrar el resultado al usuario
          document.getElementById("processingModal").style.display = "none";
          alert("Proceso terminado");
        } else if (response.status === "failed") {
          // La tarea falló
          document.getElementById("processingModal").style.display = "none";
          alert("Hubo un error en el proceso: " + response.result);
        } else if (response.status === "queued" || response.status === "deferred" || response.status === "started") {
          // La tarea aún se está ejecutando, verifica el estado de nuevo después de un tiempo
          setTimeout(checkTaskStatus, 20000);
        } else {
          alert("Estado desconocido de la tarea: " + response.status);
        }
      } else {
        alert("La respuesta del servidor no es un objeto JSON válido");
      }
    } else {
      alert("Hubo un error al comprobar el estado de la tarea, código de estado: " + status);
    }
  }
</script>
{% endblock script %}

templates/home/panel.html
{% extends 'black.html' %}
{% load static %}
{% block title %}Inicio{% endblock title %}

{% block window %}
<h1 class="text-align-center">Bienvenido!!!</h1>
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<img src="{% static 'images/panel.png' %}" alt="panel" style="width: 100%;">
{% endblock window %}

templates/home/panel_left_planos.html
{% extends 'black.html' %}
{% load static %}
{% block style %}
{% endblock style %}
{% block title %}
Archivos Planos
{% endblock title %}
{% block content %}
{% block window %}

<h1 class="text-align-center">Bienvenido!!!</h1>
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}

</ul>
{% endif %}
<img src="{% static 'images/panel.png' %}" alt="panel" style="width: 100%;">

{% endblock window %}
{% endblock content %}