adminbi/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        re_path("", include("apps.home.urls")),
        re_path("", include("apps.users.urls")),
        re_path("", include("apps.bi.urls")),
        re_path("", include("apps.cargues.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

apps/bi/urls.py
#
from django.urls import path

from . import views

app_name = "bi_app"

urlpatterns = [
    path(
        'actualizacion-bi/', 
        views.ActualizacionBiPage.as_view(),
        name='actualizacion_bi',
    ),
    # path(
    #     'reporte-bi/', 
    #     views.EmbedReportPage.as_view(),
    #     name='reporte_bi',
    # ),
    path(
        'reporte_embed/', 
        views.IncrustarBiPage.as_view(),
        name='reporte_embed',
    ),
    # path('embed_info/', views.EmbedInfoView.as_view(), name='embed_info'),
    path('reporte_embed2/', views.reporte_embed, name='reporte_embed2'),
    path('eliminar_reporte_fetched/', views.EliminarReporteFetched.as_view(), name='eliminar_reporte_fetched'),
    
]

apps/cargues/urls.py
#
from django.urls import path

from . import views

app_name = "cargues_app"

urlpatterns = [
    path(
        'cargue/', 
        views.UploadZipView.as_view(),
        name='cargue',
    ),
    path(
        'cargue_planos_tsol/', 
        views.UploadPlanoFilesView.as_view(),
        name='cargue_planos_tsol',
    )
]

apps/home/urls.py
#
from django.urls import path

from . import views

app_name = "home_app"

urlpatterns = [
    path(
        'panel/', 
        views.HomePage.as_view(),
        name='panel',
    ),
    path(
        'panel_left_planos/', 
        views.HomePage.as_view(),
        name='panel_left_planos',
    ),
    path(
        'cubo/', 
        views.CuboPage.as_view(), 
        name='cubo',
    ),
    path(
        'interface/', 
        views.InterfacePage.as_view(), 
        name='interface',
    ),
    path(
        'actualizacion/', 
        views.ActualizacionPage.as_view(), 
        name='actualizacion',
    ),
    path(
        'plano/', 
        views.PlanoPage.as_view(), 
        name='plano',
    ),
    path(
        'prueba/', 
        views.PruebaPage.as_view(), 
        name='prueba',
    ),
   path('download_file/', views.DownloadFileView.as_view(), name='download_file'),
   path('delete_file/', views.DeleteFileView.as_view(), name='delete_file'),
   path('check-task-status/', views.CheckTaskStatusView.as_view(), name='check_task_status'),
]

apps/users/urls.py
#
from django.urls import path, reverse_lazy
from django.shortcuts import redirect


from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        "login/",
        views.LoginUser.as_view(),
        name="user-login",
    ),
    # path('', lambda request: redirect('login/')),
    path("", views.home, name="home"),
    path(
        "logout/",
        views.LogoutView.as_view(),
        name="user-logout",
    ),
    path(
        "database/",
        views.DatabaseListView.as_view(),
        name="user-database",
    ),
    path(
        "base/",
        views.BaseView.as_view(),
        name="base",
    ),
    path("database/list/", views.database_list, name="database_list"),
    path(
        "register/",
        views.UserRegisterView.as_view(),
        name="user-register",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users_app:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users_app:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

templates/includes/database_selector.html
<!-- Selector de bases de datos -->
<!-- <input type="checkbox" name="" id="check" /> -->
<div class="database-selector-wrapper bg-dark">
    <div class="d-flex justify-content-center align-items-center">
        <form class="d-flex ml-auto" action="{% url form_url %}" method="post" id="FormSelectorBase">
            {% csrf_token %}
            <div class="form-group w-100">
                <select class="form-control" id="database_select" name="database_select">
                    <option disabled selected>Seleccione una empresa</option>
                    {% for database_name,database_nmEmpresa in databases_list %}
                    <option value="{{ database_name }}">{{ database_nmEmpresa }} </option>
                    {% endfor %}
                </select>
            </div>
        </form>
    </div>
</div>
<!-- Código JavaScript relacionado con el selector de bases de datos -->
<script>

    $(document).ready(function () {
        var database = window.sessionStorage.getItem("database_name");
        $.get('{% url "users_app:database_list" %}', function (data) {
            var databaseSelect = $('#database_select');
            $.each(data.database_list, function (index, database) {
                databaseSelect.append('<option value="' + database.database_name + '">' + database.database_nmEmpresa + '</option>');
            });

            if (database) {
                updateDatabaseName(database);
                document.getElementById("database_select").value = database;


            }
        });

        document.getElementById("database_select").addEventListener("change", function () {
            var select = this;
            database = select.options[select.selectedIndex].value;
            window.sessionStorage.setItem("database_name", database);
            updateDatabaseName(database);
        });
    });

    function updateDatabaseName(newDatabase) {
        console.log("Updating database name:", newDatabase);
        var csrfToken = document.getElementsByName("csrfmiddlewaretoken")[0].value;
        var xhr = new XMLHttpRequest();
        xhr.open("POST", "{% url form_url %}", true);
        xhr.setRequestHeader("X-CSRFToken", csrfToken);
        xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        xhr.onreadystatechange = function () {
            if (this.readyState === XMLHttpRequest.DONE) {
                if (this.status === 200) {
                    console.log("Database name updated successfully:", newDatabase);
                    database = newDatabase;
                } else {
                    console.log("Error al actualizar el valor de database_name en la sesión:", this.status, this.responseText);
                }
            }
        };
        xhr.send("database_select=" + encodeURIComponent(newDatabase));
    }

</script>

templates/includes/datepicker_range.html
<script type="text/javascript">
$(function() {

    var start = moment().startOf('month');
    var end = moment().endOf('month');
    function cb(start, end) {
    // $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    $('#reportrange span').html('El Rango de Fecha Selecionado es:');
    $('#IdtReporteIni').val(start.format('YYYY-MM-DD'));
    $('#IdtReporteFin').val(end.format('YYYY-MM-DD'));
    }

    $('#reportrange').daterangepicker({
        startDate: start,
        endDate: end,
        ranges: {
           'Hoy': [moment(), moment()],
           'Ayer': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Últimos 7 Días': [moment().subtract(6, 'days'), moment()],
           'Últimos 30 Días': [moment().subtract(29, 'days'), moment()],
           'Este Mes': [moment().startOf('month'), moment().endOf('month')],
           'Mes Anterior': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
    }, cb);

    cb(start, end);

});
</script>

templates/includes/download_file.html
<a id="download_file" class="d-none" href="{% url 'home_app:download_file' %}">Descargar archivo</a>

templates/includes/left_sidebar.html
<!-- {% if perms.permisos.nav_bar %} -->
{% load static %}


<!-- Barra lateral -->
<div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
  <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
    <!-- Logo y Nombre de Usuario -->
    <a href="{% url 'home_app:panel' %}"
      class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <img src="{% static 'images/Logo-Blanco.png' %}" alt="Logo" width="30" height="30" class="rounded-circle">
      <span class="fs-5 ms-2 d-none d-sm-inline">{{ user.get_full_name }}</span>
    </a>
    <!-- Enlaces de Navegación -->
    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start">
      {% if perms.permisos.cubo %}
      <li class="nav-item">
        <a class="nav-link text-white align-middle px-0" href="{% url 'home_app:cubo'%}">
          <i class="fas fa-cube me-2"></i> <span class="ms-1 d-none d-sm-inline">Cubo de Ventas</span>
        </a>
      </li>
      {% endif %}
      {% if perms.permisos.interface %}
      <li class="nav-item">
        <a href="{% url 'home_app:interface'%}" class="nav-link text-white align-middle px-0">
          <i class="fas fa-desktop me-2"></i> <span class="ms-1 d-none d-sm-inline">Int. Contables</span>
        </a>
      </li>
      {% endif %}
      {% if perms.permisos.plano %}
      <li class="nav-item">
        <a href="{% url 'home_app:plano'%}" class="nav-link text-white align-middle px-0">
          <i class="fas fa-table me-2"></i> <span class="ms-1 d-none d-sm-inline">Archivos Planos</span>
        </a>
      </li>
      {% endif %}
      {% if perms.permisos.plano_tsol %}
      <li class="nav-item">
        <a href="{% url 'cargues_app:cargue'%}" class="nav-link text-white align-middle px-0">
          <i class="fas fa-table me-2"></i> <span class="ms-1 d-none d-sm-inline">Cargue Planos Zip</span>
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'cargues_app:cargue_planos_tsol'%}" class="nav-link text-white align-middle px-0">
          <i class="fas fa-table me-2"></i> <span class="ms-1 d-none d-sm-inline">Cargue Planos Tsol</span>
        </a>
      </li>
      {% endif %}
      {% if perms.permisos.actualizar_base %}
      <li class="nav-item">
        <a href="{% url 'home_app:actualizacion'%}" class="nav-link text-white align-middle px-0">
          <i class="fas fa-th me-2"></i><span class="ms-1 d-none d-sm-inline">Actualización Datos</span>
        </a>
      </li>
      {% endif %}
      {% if perms.permisos.admin %}
      <li class="nav-item">
        <a href="{% url 'admin:index' %}" class="nav-link text-white align-middle px-0">
          <i class="fas fa-sliders-h me-2"></i> <span class="ms-1 d-none d-sm-inline">Configuración</span>
        </a>
      </li>
      {% endif %}
      <!-- Agrega más elementos de menú aquí según sea necesario -->
    </ul>

    <hr>

    <!-- Área de Usuario y Dropdown -->
    <div class="dropdown pb-4">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1"
        data-bs-toggle="dropdown" aria-expanded="false">
        <img src="{% static 'images/user-profile.png' %}" alt="profile" width="30" height="30" class="rounded-circle">
        <span class="d-none d-sm-inline mx-1">{{ user.username }}</span>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        <!-- Agrega elementos al dropdown según sea necesario -->
        {% if user.is_authenticated %}
        <li><a class="dropdown-item" href="{% url 'users_app:user-logout' %}">Sign out</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>




<!-- {% endif %} -->

templates/includes/menu_items.html
<!-- menu_items.html -->
<nav>
  <ul class="navbar-nav flex-column">
    {% if perms.permisos.cubo %}
    <li class="nav-item">
      <a class="nav-link text-white" href="{% url 'home_app:cubo'%}"><i class="fas fa-cube"></i><span> Cubo de
          Ventas</span></a>
    </li>
    {% endif %}
    {% if perms.permisos.interface %}
    <li class="nav-item">
      <a class="nav-link text-white" href="{% url 'home_app:interface'%}"><i class="fas fa-desktop"></i><span> Int.
          Contables</span></a>
    </li>
    {% endif %}
    {% if perms.permisos.plano %}
    <li class="nav-item">
      <a class="nav-link text-white" href="{% url 'home_app:plano'%}"><i class="fas fa-table"></i><span> Archivos
          Planos</span></a>
    </li>
    {% endif %}
    {% if perms.permisos.actualizar_base %}
    <li class="nav-item">
      <a class="nav-link text-white" href="{% url 'home_app:actualizacion'%}"><i class="fas fa-th"></i><span>
          Actualización Datos</span></a>
    </li>
    {% endif %}
    {% if perms.permisos.admin %}
    <li class="nav-item">
      <a class="nav-link text-white" href="{% url 'admin:index' %}"><i class="fas fa-sliders-h"></i><span>
          Configuración</span></a>
    </li>
    {% endif %}
  </ul>
</nav>

templates/includes/menu_items_planos.html
<!-- menu_items.html -->
<nav>
  <ul class="navbar-nav flex-column">
    {% if perms.permisos.cubo %}
    <li class="nav-item">
      <a class="nav-link text-white" href="{% url 'home_app:cubo'%}"><i class="fas fa-cube"></i><span> Cubo de
          Ventas</span></a>
    </li>
    {% endif %}
    {% if perms.permisos.interface %}
    <li class="nav-item">
      <a class="nav-link text-white" href="{% url 'home_app:interface'%}"><i class="fas fa-desktop"></i><span> Int.
          Contables</span></a>
    </li>
    {% endif %}
    {% if perms.permisos.plano %}
    <li class="nav-item">
      <a class="nav-link text-white" href="{% url 'home_app:plano'%}"><i class="fas fa-table"></i><span> Archivos
          Planos</span></a>
    </li>
    {% endif %}
    {% if perms.permisos.actualizar_base %}
    <li class="nav-item">
      <a class="nav-link text-white" href="{% url 'home_app:actualizacion'%}"><i class="fas fa-th"></i><span>
          Actualización Datos</span></a>
    </li>
    {% endif %}
    {% if perms.permisos.admin %}
    <li class="nav-item">
      <a class="nav-link text-white" href="{% url 'admin:index' %}"><i class="fas fa-sliders-h"></i><span>
          Configuración</span></a>
    </li>
    {% endif %}
  </ul>
</nav>

templates/includes/top_nav.html
{% load static %}
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <!-- Branding/Logo -->
            <a class="navbar-brand" href="{% url 'home_app:panel' %}">
                <img src="{% static 'images/Logo-Blanco.png' %}" alt="Logo" style="height: 30px;">
            </a>

            <!-- Toggler for Mobile -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Navbar Links -->
            <div class="collapse navbar-collapse" id="navbarNavDropdown">

                <!-- Menú para la barra superior -->
                <ul class="navbar-nav ms-auto">

                    {% if perms.permisos.informe_bi %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'bi_app:reporte_embed' %}"><i
                                class="fas fa-tachometer-alt"></i><span>Dashboard PowerBI</span></a>
                    </li>
                    {% endif %}
                    {% if perms.permisos.informe_bi %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'home_app:panel_left_planos' %}"><i
                                class="fas fa-tachometer-alt"></i><span>Arch. Planos</span></a>
                    </li>
                    {% endif %}
                    <!-- <li class="nav-item active">
                        <a class="nav-link text-white" href="#"><i class="far fa-address-book"></i>Address Book</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#"><i class="far fa-clone"></i>Components</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#"><i class="far fa-calendar-alt"></i>Calendar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#"><i class="far fa-chart-bar"></i>Charts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#"><i class="far fa-copy"></i>Documents</a>
                    </li> -->
                </ul>

                <!-- Logout Button -->
                {% if user.is_authenticated %}
                <a href="{% url 'users_app:user-logout' %}" class="logout-btn">Logout <i
                        class="fas fa-sign-out-alt"></i></a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>