adminbi/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        re_path("", include("apps.home.urls")),
        re_path("", include("apps.users.urls")),
        re_path("", include("apps.bi.urls")),
        re_path("", include("apps.cargues.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

apps/users/urls.py
#
from django.urls import path, reverse_lazy
from django.shortcuts import redirect


from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        "login/",
        views.LoginUser.as_view(),
        name="user-login",
    ),
    # path('', lambda request: redirect('login/')),
    path("", views.home, name="home"),
    path(
        "logout/",
        views.LogoutView.as_view(),
        name="user-logout",
    ),
    path(
        "database/",
        views.DatabaseListView.as_view(),
        name="user-database",
    ),
    path(
        "base/",
        views.BaseView.as_view(),
        name="base",
    ),
    path("database/list/", views.database_list, name="database_list"),
    path(
        "register/",
        views.UserRegisterView.as_view(),
        name="user-register",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users_app:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users_app:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <link rel="icon" type="image/ico" href="{% static 'images/Iconologo.ico' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
    integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js"
    integrity="sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i"
    crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

  {% block head %}{% endblock head %}
  {% block style %}{% endblock style %}
  <title>Interface | {% block title %}{% endblock title %}</title>
</head>

<body>
  {% block selector_base %}
  {% endblock selector_base %}
  {% block barra_superior %}
  {% endblock barra_superior %}
  {% block content %}
  {% block barra_lateral %}
  {% endblock barra_lateral %}
  {% block window %}
  {% endblock window %}
  {% endblock content %}
  {% block script %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"
    integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  {% endblock script %}
</body>

</html>

templates/black.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />

{% endblock head %}

{% block style %}
{% endblock style %}
{% block title %}
{% endblock title %}
{% block selector_base %}
{% include 'includes/database_selector.html' %}
{% endblock selector_base %}

{% block barra_superior %}
{% include 'includes/top_nav.html' %}
{% endblock barra_superior %}


{% block content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        {% block barra_lateral %}
        {% include 'includes/left_sidebar.html' %}
        {% endblock barra_lateral %}

        <div class="col">
            {% block window %}
            {% endblock window %}
        </div>
    </div>
</div>
{% endblock content %}
{% block script %}

{% endblock script %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Inicio
{% endblock title %}

{% block content %}
<style>
    .background-container::before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.4);
        z-index: 1;
    }
</style>
<div class="container-fluid position-relative background-container"
    style="height: 100vh; background-image: url('{% static 'images/background-image.png' %}'); background-size: cover;">
    <div class="d-flex flex-column align-items-center h-100" style="position: relative; z-index: 2;">
        <div class="row">
            <div class="col">
                <div class="card mx-auto bg-transparent border-0" style="width: 150px; height: 150px;">
                    <img src="{% static 'images/Logo-DataZenith.png' %}" class="card-img-top img-fluid rounded-circle"
                        style="width: 150px; height: 150px; background-color: #f0f0f0;" alt="Logo-Bi">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="card mx-auto bg-transparent border-0" style="width: 150px; height: 150px;">
                    <img src="{% static 'images/Logo-Cerebro-Bi.png' %}" class="card-img-top img-fluid rounded-circle"
                        style="width: 150px; height: 150px; background-color: #f0f0f0;" alt="Logo-DataZenith">
                </div>
            </div>
            <div class="col-6">
                <div class="card mx-auto bg-transparent border-0" style="width: 150px; height: 150px;">
                    <img src="{% static 'images/Logo-Bi.png' %}" class="card-img-top img-fluid rounded-circle"
                        style="width: 150px; height: 150px; background-color: #f0f0f0;" alt="Logo-Sidis">
                </div>
            </div>
        </div>
    </div>
    <div class="position-absolute" style="top: 80%; left: 50%; transform: translate(-50%, -50%); z-index: 2;">
        <h1 class="text-center text-white" style="font-size: 5rem;">Interface</h1>
        <h3 class="text-center text-white" style="font-size: 3rem;">BI Solutions</h3>
    </div>
    <a href="{% url 'users_app:user-login' %}" class="btn btn-primary position-absolute"
        style="top: 15px; right: 15px; z-index: 2;">Ir a Login</a>
</div>
{% endblock content %}