adminbi/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        re_path("", include("apps.home.urls")),
        re_path("", include("apps.users.urls")),
        re_path("", include("apps.bi.urls")),
        re_path("", include("apps.cargues.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

apps/users/urls.py
#
from django.urls import path, reverse_lazy
from django.shortcuts import redirect


from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        "login/",
        views.LoginUser.as_view(),
        name="user-login",
    ),
    # path('', lambda request: redirect('login/')),
    path("", views.home, name="home"),
    path(
        "logout/",
        views.LogoutView.as_view(),
        name="user-logout",
    ),
    path(
        "database/",
        views.DatabaseListView.as_view(),
        name="user-database",
    ),
    path(
        "base/",
        views.BaseView.as_view(),
        name="base",
    ),
    path("database/list/", views.database_list, name="database_list"),
    path(
        "register/",
        views.UserRegisterView.as_view(),
        name="user-register",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users_app:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users_app:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

apps/users/models.py
from django.db import models
from django.db.models import JSONField
from django.conf import settings

# Create your models here.
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from .managers import UserManager

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from apps.permisos.models import ConfEmpresas

# class Database(models.Model):
#     name = models.CharField(max_length=100)

#     def __str__(self):
#         return self.name


class User(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOISES = (
        ("M", "Masculino"),
        ("F", "Femenino"),
        ("O", "Otros"),
    )
    username = models.CharField(max_length=10, unique=True, verbose_name="Usuario")
    email = models.EmailField(verbose_name="e-mail")
    nombres = models.CharField(max_length=50, verbose_name="Nombres")
    apellidos = models.CharField(max_length=50, verbose_name="Apellidos")
    genero = models.CharField(
        max_length=1, choices=GENDER_CHOISES, blank=True, verbose_name="Género"
    )
    codregistro = models.CharField(
        max_length=6, blank=True, verbose_name="Código de Registro"
    )
    conf_empresas = models.ManyToManyField(
        ConfEmpresas, blank=True, verbose_name="Bases de datos"
    )
    #
    is_staff = models.BooleanField(default=False, verbose_name="Administrador")
    is_active = models.BooleanField(default=False, verbose_name="Activo")
    is_superuser = models.BooleanField(default=False, verbose_name="Superusuario")

    USERNAME_FIELD = "username"

    REQUIRED_FIELDS = ["email"]

    objects = UserManager()

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return self.nombres + " " + self.apellidos

    def __str__(self):
        return (
            self.username
            + " - "
            + self.nombres
            + " - "
            + self.apellidos
            + " - "
            + self.email
        )


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    conf_empresas = models.ManyToManyField(ConfEmpresas)


class RegistroAuditoria(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    fecha_hora = models.DateTimeField(auto_now_add=True)
    ip = models.GenericIPAddressField()
    transaccion = models.CharField(max_length=255)
    detalle = JSONField()
    database_name = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return (
            self.fecha_hora.strftime("%Y-%m-%d %H:%M:%S")
            + " - "
            + self.database_name
            + " - "
            + self.user.get_full_name()
            + " - "
            + (str(self.city) if self.city else "")
        )

    class Meta:
        db_table = "registro_auditoria"
        verbose_name = "Registro de Auditoria"
        verbose_name_plural = "Registro de Auditorias"

apps/users/forms.py
from django import forms
from django.contrib.auth import authenticate

from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
#
from .models import User


class UserRegisterForm(forms.ModelForm):
    password1 = forms.CharField(
        label="Contraseña",
        required=True,
        widget=forms.PasswordInput(attrs={"placeholder": "Contraseña"}),
    )
    password2 = forms.CharField(
        label="Contraseña",
        required=True,
        widget=forms.PasswordInput(attrs={"placeholder": "Repetir Contraseña"}),
    )

    class Meta:
        """Meta definition for Userform."""

        model = User
        fields = (
            "username",
            "email",
            "nombres",
            "apellidos",
            "genero",
        )

    def clean_password2(self):
        if self.cleaned_data["password1"] != self.cleaned_data["password2"]:
            self.add_error("password2", "Las contraseñas no son iguales")


class LoginForm(forms.Form):
    username = forms.CharField(
        label="Usuario",
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Usuario",
            }
        ),
    )
    password = forms.CharField(
        label="Contraseña",
        required=True,
        widget=forms.PasswordInput(attrs={"placeholder": "Contraseña"}),
    )

    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)
    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data["username"]
        password = self.cleaned_data["password"]

        if not authenticate(username=username, password=password):
            raise forms.ValidationError("Los datos de usuario no son correctos")

        return self.cleaned_data


class UpdatePasswordForm(forms.Form):
    password1 = forms.CharField(
        label="Contraseña",
        required=True,
        widget=forms.PasswordInput(attrs={"placeholder": "Contraseña Actual"}),
    )
    password2 = forms.CharField(
        label="Contraseña",
        required=True,
        widget=forms.PasswordInput(attrs={"placeholder": "Contraseña Nueva"}),
    )


class VerificationForm(forms.Form):
    codregistro = forms.CharField(required=True)

    def __init__(self, pk, *args, **kwargs):
        self.id_user = pk
        super(VerificationForm, self).__init__(*args, **kwargs)

    def clean_codregistro(self):
        codigo = self.cleaned_data["codregistro"]

        if len(codigo) == 6:
            # verificamos si el codigo y el id de usuario son validos:
            activo = User.objects.cod_validation(self.id_user, codigo)
            if not activo:
                raise forms.ValidationError("el codigo es incorrecto")
        else:
            raise forms.ValidationError("el codigo es incorrecto")

apps/users/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator

# from apps.users.decorators import registrar_auditoria
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from scripts.StaticPage import StaticPage


from django.views.generic import (
    View,
    CreateView,
    ListView,
    TemplateView,
)

from django.views.generic.edit import (
    FormView,
)

from .forms import UserRegisterForm, LoginForm, UpdatePasswordForm, VerificationForm

#
from .models import User
from apps.permisos.models import ConfEmpresas

#
from .functions import code_generator


class UserRegisterView(FormView):
    template_name = "users/register.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy("users_app:user-login")

    def form_valid(self, form):
        # generamos el codigo
        # codigo = code_generator()
        #
        user = User.objects.create_user(
            form.cleaned_data["username"],
            form.cleaned_data["email"],
            form.cleaned_data["password1"],
            nombres=form.cleaned_data["nombres"],
            apellidos=form.cleaned_data["apellidos"],
            genero=form.cleaned_data["genero"],
            # codregistro=codigo
        )
        # # enviar el codigo al email del user
        # asunto = 'Confirmación de email'
        # mensaje = 'Codigo de verificación: ' + codigo
        # email_remitente = 'torredecontrolamovil@gmail.com'
        # #
        # send_mail(asunto, mensaje, email_remitente, [form.cleaned_data['email'],])
        # # redirigir a pantalla de valdiacion

        # return HttpResponseRedirect(
        #     reverse(
        #         'users_app:user-verification',
        #         kwargs={'pk': user.id}
        #     )
        # )
        return HttpResponseRedirect(reverse("users_app:user-login"))


class LoginUser(FormView):
    template_name = "users/login.html"
    form_class = LoginForm
    success_url = reverse_lazy("home_app:panel")

    def form_valid(self, form):
        user = authenticate(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password"],
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):
    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(reverse("users_app:user-login"))


class CodeVerificationView(FormView):
    template_name = "users/verification.html"
    form_class = VerificationForm
    success_url = reverse_lazy("users_app:user-login")

    def get_form_kwargs(self):
        kwargs = super(CodeVerificationView, self).get_form_kwargs()
        kwargs.update(
            {
                "pk": self.kwargs["pk"],
            }
        )
        return kwargs

    def form_valid(self, form):
        #
        User.objects.filter(id=self.kwargs["pk"]).update(is_active=True)
        return super(CodeVerificationView, self).form_valid(form)


class BaseView(TemplateView):
    template_name = "base.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        databases = self.request.user.conf_empresas.all().order_by("nmEmpresa")
        database_list = [
            {"name": database.name, "nmEmpresa": database.nmEmpresa}
            for database in databases
        ]
        sorted_database_list = sorted(database_list, key=lambda x: x["nmEmpresa"])
        database_name = self.request.session.get(
            "database_name"
        ) or self.request.POST.get("database_select")
        context["database_list"] = sorted_database_list
        context["database_name"] = database_name
        return context

    def post(self, request, *args, **kwargs):
        database_name = request.POST.get("database_select")
        print(f"Received database_name: {database_name}")
        if database_name:
            request.session["database_name"] = database_name
            return JsonResponse(
                {"status": "success", "message": "Database name updated in session."}
            )
        else:
            return JsonResponse(
                {"status": "error", "message": "Invalid database name provided."},
                status=400,
            )


class DatabaseListView(ListView):
    model = ConfEmpresas
    context_object_name = "databases"
    template_name = "includes/database_list.html"

    def get_queryset(self):
        return self.request.user.conf_empresas.all().order_by("nmEmpresa")


def database_list(request):
    databases = request.user.conf_empresas.all().order_by("nmEmpresa")
    database_list = [
        {"database_name": database.name, "database_nmEmpresa": database.nmEmpresa}
        for database in databases
    ]
    return JsonResponse({"database_list": database_list})


def home(request):
    return render(request, "index.html")

templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Login
{% endblock title %}

{% block content %}
<div class="container vh-100">
    <div class="row align-items-center h-100">
        <div class="col-md-6">
            <img src="{% static 'images/imagen-login.png' %}" class="img-fluid" style="max-width: 100%; height: auto;"
                alt="Logo-DataZenith">
        </div>
        <div class="col-md-6">
            <div class="card shadow-lg p-3 mb-5 bg-white rounded">
                <div class="card-body">
                    <div class="text-center mb-4">
                        <img src="{% static 'images/Logo-DataZenith.png' %}" class="brand_logo img-thumbnail"
                            style="max-width: 200px; height: auto;" alt="Logo">
                        <h3>Interface</h3>
                    </div>
                    {% if form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ form.non_field_errors }}
                    </div>
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="{{ form.username.id_for_label }}" class="form-label"><i class="fa fa-user"></i>
                                Usuario</label>
                            <input type="text" class="form-control" id="{{ form.username.id_for_label }}"
                                name="{{ form.username.html_name }}" value="{{ form.username.value|default:'' }}"
                                required>
                        </div>
                        {% for error in form.username.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                        {% endfor %}
                        <div class="mb-3">
                            <label for="{{ form.password.id_for_label }}" class="form-label"><i class="fa fa-lock"></i>
                                Contraseña</label>
                            <input type="password" class="form-control" id="{{ form.password.id_for_label }}"
                                name="{{ form.password.html_name }}" required>
                        </div>
                        {% for error in form.password.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                        {% endfor %}
                        <div class="mb-3 form-check">
                            <input type="checkbox" class="form-check-input" id="rememberMe">
                            <label class="form-check-label" for="rememberMe">Recuérdame</label>
                        </div>
                        <div>
                            {{ form.captcha }}
                        </div>
                        <div class="mb-3">
                            <a href="{% url 'users_app:password_reset' %}">¿Olvidaste tu contraseña?</a>
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                        <a href="{% url 'users_app:user-register' %}" class="btn btn-secondary">Registrarse</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock content %}

templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Contraseña restablecida
{% endblock title %}

{% block content %}
<div class="container vh-100">
    <div class="row align-items-center h-100">
        <div class="col-md-12 text-center">
            <h3>Tu contraseña ha sido restablecida con éxito.</h3>
            <p><a href="{% url 'users_app:user-login' %}">Iniciar sesión</a> con tu nueva contraseña.</p>
        </div>
    </div>
</div>
{% endblock content %}

templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Restablecer contraseña
{% endblock title %}

{% block content %}
<div class="container vh-100">
    <div class="row align-items-center h-100">
        <div class="col-md-6">
            <img src="{% static 'images/imagen-login.png' %}" class="img-fluid" style="max-width: 100%; height: auto;"
                alt="Logo">
        </div>
        <div class="col-md-6">
            <div class="card shadow-lg p-3 mb-5 bg-white rounded">
                <div class="card-body">
                    <div class="text-center mb-4">
                        <img src="{% static 'images/Logo-DataZenith.png' %}" class="brand_logo img-thumbnail"
                            style="max-width: 200px; height: auto;" alt="Logo">
                        <h3>Restablecer contraseña</h3>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Restablecer contraseña</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Enlace enviado
{% endblock title %}

{% block content %}
<div class="container vh-100">
    <div class="row align-items-center h-100">
        <div class="col-md-12 text-center">
            <h3>Se ha enviado un enlace de recuperación de contraseña a tu correo electrónico.</h3>
            <p>Revisa tu correo electrónico y sigue las instrucciones para restablecer tu contraseña.</p>
        </div>
    </div>
</div>
{% endblock content %}

templates/users/password_reset_email.html
{% autoescape off %}
Hola {{ user.nombres }},

Haz clic en el siguiente enlace para restablecer tu contraseña:

https://interface.amovil.com.co{% url 'users_app:password_reset_confirm' uidb64=uid token=token %}

Si no has solicitado restablecer tu contraseña, ignora este correo electrónico.

Saludos,
El equipo de Interface Amovil
{% endautoescape %}

templates/users/password_reset_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Recuperar contraseña
{% endblock title %}

{% block content %}
<div class="container vh-100">
    <div class="row align-items-center h-100">
        <div class="col-md-6">
            <img src="{% static 'images/imagen-login.png' %}" class="img-fluid" style="max-width: 100%; height: auto;"
                alt="Logo">
        </div>
        <div class="col-md-6">
            <div class="card shadow-lg p-3 mb-5 bg-white rounded">
                <div class="card-body">
                    <div class="text-center mb-4">
                        <img src="{% static 'images/Logo-DataZenith.png' %}" class="brand_logo img-thumbnail"
                            style="max-width: 200px; height: auto;" alt="Logo">
                        <h3>Recuperar contraseña</h3>
                    </div>
                    <form method="post" action="{% url 'users_app:password_reset' %}">
                        {% csrf_token %}
                        {{ form.email.label_tag }} {{ form.email }}
                        <button type="submit" class="btn btn-primary">Enviar enlace de recuperación</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/users/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Registro
{% endblock title %}

{% block content %}
<div class="container vh-100">
    <div class="row align-items-center h-100">
        <div class="col-md-6">
            <img src="{% static 'images/imagen-login.png' %}" class="img-fluid" style="max-width: 100%; height: auto;"
                alt="Logo">
        </div>
        <div class="col-md-6">
            <div class="card shadow-lg p-3 mb-5 bg-white rounded">
                <div class="card-body">
                    <div class="text-center mb-4">
                        <img src="{% static 'images/Logo-DataZenith.png' %}" class="brand_logo img-thumbnail"
                            style="max-width: 200px; height: auto;" alt="Logo">
                        <h3>Registrar Nuevo Usuario</h3>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="{{ form.username.id_for_label }}" class="form-label">Usuario</label>
                            <input type="text" class="form-control" id="{{ form.username.id_for_label }}"
                                name="{{ form.username.html_name }}" value="{{ form.username.value|default:'' }}"
                                required>
                        </div>
                        {% for error in form.username.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                        {% endfor %}
                        <div class="mb-3">
                            <label for="{{ form.email.id_for_label }}" class="form-label">E-mail</label>
                            <input type="email" class="form-control" id="{{ form.email.id_for_label }}"
                                name="{{ form.email.html_name }}" value="{{ form.email.value|default:'' }}" required>
                        </div>
                        {% for error in form.email.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                        {% endfor %}
                        <div class="mb-3">
                            <label for="{{ form.nombres.id_for_label }}" class="form-label">Nombres</label>
                            <input type="text" class="form-control" id="{{ form.nombres.id_for_label }}"
                                name="{{ form.nombres.html_name }}" value="{{ form.nombres.value|default:'' }}"
                                required>
                        </div>
                        {% for error in form.nombres.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                        {% endfor %}
                        <div class="mb-3">
                            <label for="{{ form.apellidos.id_for_label }}" class="form-label">Apellidos</label>
                            <input type="text" class="form-control" id="{{ form.apellidos.id_for_label }}"
                                name="{{ form.apellidos.html_name }}" value="{{ form.apellidos.value|default:'' }}"
                                required>
                        </div>
                        {% for error in form.apellidos.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                        {% endfor %}
                        <div class="mb-3">
                            <label for="{{ form.genero.id_for_label }}" class="form-label">Género</label>
                            {{ form.genero }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.password1.id_for_label }}" class="form-label">Contraseña</label>
                            <input type="password" class="form-control" id="{{ form.password1.id_for_label }}"
                                name="{{ form.password1.html_name }}" required>
                        </div>
                        {% for error in form.password1.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                        {% endfor %}
                        <div class="mb-3">
                            <label for="{{ form.password2.id_for_label }}" class="form-label">Repetir Contraseña</label>
                            <input type="password" class="form-control" id="{{ form.password2.id_for_label }}"
                                name="{{ form.password2.html_name }}" required>
                        </div>
                        {% for error in form.password2.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">Registrar</button>
                        <a href="{% url 'users_app:user-login' %}" class="btn btn-secondary">Ir a Login</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/users/update.html
{% extends 'base.html' %}
{% block title %}
Login
{% endblock title %}

{% block content %}
    <h1>Cambiar Contraseña: {{ user.get_full_name }}</h1>
    <form method="post">{% csrf_token %}
        {{form.as_p}}
        <button type="submit">Actualziar</button>
    </form>
{% endblock content %}

templates/users/verification.html
{% extends 'base.html' %}
{% block title %}
Login
{% endblock title %}

{% block content %}
    <h1>Verificacion de email</h1>
    <h3>Ingre el codigo de Verificacion:</h3>
    <form method="post">{% csrf_token %}
        {{form.as_p}}
        <button type="submit">Confirmar</button>
    </form>
{% endblock content %}